####### AUTOMATION #######
# Verisure automation
  - alias: Alarm status changed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
    action:
      - service: notify.notify
        data_template:
          message: >
            Alarm changed from {{ trigger.from_state.state }}
            to {{ trigger.to_state.state }}
            by {{ trigger.to_state.attributes.changed_by }}

# Turn off lights when alarm is in home mode
  - alias: Alarm status home mode
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
        from: 'disarmed'
        to: 'armed_home'
        state: 'Night mode'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_front_door
      - service: homeassistant.turn_off
        entity_id:
          - switch.dining_room_aquarium
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_driveway
      - service: homeassistant.turn_off
        entity_id:
          - switch.hallway_stairs
      - service: homeassistant.turn_off
        entity_id:
          - light.living_room_window_light
      - service: homeassistant.turn_off
        entity_id:
          - switch.hallway_stairs
      - service: homeassistant.turn_off
        entity_id:
          - light.tv_bench


  ####### FRONT DOOR ######
  - alias: Turn on front door light at sunset
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunset
    # Optional time offset. This example is 45 minutes.
        offset: '-00:20:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_front_door

  - alias: Turn off front door light at 23:00
    trigger:
      - platform: time
        after: '23:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_front_door

  - alias: Turn on front door light at 06:30
    trigger:
      - platform: time
        after: '06:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_front_door

  - alias: Turn off front door light at sunrise
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunrise
    # Optional time offset. This example is 45 minutes.
        offset: '+00:20:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_front_door


  ####### AQUARIUM ######
  - alias: Turn on aquarium at 07:00
    trigger:
      - platform: time
        after: '07:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.dining_room_aquarium

  - alias: Turn off aquarium at 21:30
    trigger:
      - platform: time
        after: '21:30:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.dining_room_aquarium

  ####### DRIVEWAY ######
  - alias: Turn on DRIVEWAY light at sunset
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunset
    # Optional time offset. This example is 45 minutes.
        offset: '+00:40:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_driveway

  - alias: Turn off DRIVEWAY light at 22:00
    trigger:
      - platform: time
        after: '22:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_driveway

  - alias: Turn on DRIVEWAY light at 07:00
    trigger:
      - platform: time
        after: '07:00:00'
    condition:
      - condition: template
        value_template: '{{ states.sun.sun.attributes.elevation < 0 }}' #only if sun is down
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_driveway

  - alias: Turn off DRIVEWAY light at sunrise
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunrise
    # Optional time offset. This example is 45 minutes.
        offset: '+00:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_driveway

  ####### STAIRS ######
  - alias: Turn on Stairs light at sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:10:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_stairs

  - alias: Turn off Stairs light at 23:00
    trigger:
      - platform: time
        after: '23:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.hallway_stairs

  - alias: Turn on Stairs light at 06:30
    trigger:
      - platform: time
        after: '06:30:00'
    condition:
      - condition: template
        value_template: '{{ states.sun.sun.attributes.elevation < 0 }}' #only if sun is down
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_stairs

  - alias: Turn off Stairs light at sunrise
    trigger:
      - platform: sun
        event: sunrise
        offset: '00:01:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.hallway_stairs

  ### Dim the Bedroom bedside lights when getting closer to bed - but never higher than it's already set
  - alias: Bedside 50% at 22:00
    trigger:
      - platform: time
        after: '22:00:00'
    condition:
      - condition: numeric_state
        entity_id: light.bedside
        value_template: '{% if states.light.bedside.state == "on"  %}{{ states.light.bedside.attributes.brightness }}{% else %}0{% endif %}'
        above: 144
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.bedside
        data:
          brightness: 144
          rgb_color: [243, 179, 80]

  - alias: Bedside 25% at 22:30
    trigger:
      - platform: time
        after: '22:30:00'
    condition:
      - condition: numeric_state
        entity_id: light.bedside
        value_template: '{% if states.light.bedside.state == "on"  %}{{ states.light.bedside.attributes.brightness }}{% else %}0{% endif %}'
        above: 64
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.bedside
        data:
          brightness: 64
          rgb_color: [243, 179, 80]

  - alias: Bedside 10% at 22:45
    trigger:
      - platform: time
        after: '22:45:00'
    condition:
      - condition: numeric_state
        entity_id: light.bedside
        value_template: '{% if states.light.bedside.state == "on"  %}{{ states.light.bedside.attributes.brightness }}{% else %}0{% endif %}'
        above: 25
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.bedside
        data:
          brightness: 25
          rgb_color: [243, 179, 80]

  - alias: Bedside 5% at 23:00
    trigger:
      - platform: time
        after: '23:00:00'
    condition:
      - condition: numeric_state
        entity_id: light.bedside
        value_template: '{% if states.light.bedside.state == "on"  %}{{ states.light.bedside.attributes.brightness }}{% else %}0{% endif %}'
        above: 12
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.bedside
        data:
          brightness: 12
          rgb_color: [243, 179, 80]

  - alias: Bedside off at 23:15
    trigger:
      - platform: time
        after: '23:15:00'
    condition:
      - condition: numeric_state
        entity_id: light.bedside
        value_template: '{% if states.light.bedside.state == "on"  %}{{ states.light.bedside.attributes.brightness }}{% else %}0{% endif %}'
        above: 0
    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.bedside

#### Upper Hallway ##
  - alias: Upstairs hallway 10% at 23:00
    trigger:
      - platform: time
        after: '23:00:00'
    condition:
      - condition: numeric_state
        entity_id: light.upstairs_hallway
        value_template: '{% if states.light.upstairs_hallway.state == "on"  %}{{ states.light.upstairs_hallway.attributes.brightness }}{% else %}0{% endif %}'
        above: 25
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.upstairs_hallway
        data:
          brightness: 25

  - alias: Upstairs hallway 30% at 21:00
    trigger:
      - platform: time
        after: '21:00:00'
    condition:
      - condition: numeric_state
        entity_id: light.upstairs_hallway
        value_template: '{% if states.light.upstairs_hallway.state == "on"  %}{{ states.light.upstairs_hallway.attributes.brightness }}{% else %}0{% endif %}'
        above: 50
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.upstairs_hallway
        data:
          brightness: 50

  - alias: Turn off upper hallway light at sunrise
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunrise
    # Optional time offset. This example is 45 minutes.
        offset: '+00:30:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.upstairs_hallway

  - alias: Turn on upper hallway light at sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:10:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.upstairs_hallway
        data:
          brightness: 180


  ######## Mailbox automations #######
  - alias: Turn on mailbox inside light when hatch open
    trigger:
      - platform: state
        entity_id: sensor.mailbox_hatch
        state: 'open'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.mailbox_inside_light
  - alias: Turn off mailbox inside light when hatch closed
    trigger:
      - platform: state
        entity_id: sensor.mailbox_hatch
        state: 'closed'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.mailbox_inside_light
  - alias: Turn on mailbox inside light when door open
    trigger:
      - platform: state
        entity_id: sensor.mailbox_door
        state: 'open'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.mailbox_inside_light
  - alias: Turn off mailbox inside light when door closed
    trigger:
      - platform: state
        entity_id: sensor.mailbox_door
        state: 'closed'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.mailbox_inside_light

  - alias: Turn off mailbox outside light at sunrise
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunrise
    # Optional time offset. This example is 45 minutes.
        offset: '+00:30:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.mailbox_outside_light

  - alias: Turn on mailbox outside light at sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:10:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.mailbox_outside_light

  - alias: Notify via email when hatch open
    trigger:
      - platform: state
        entity_id: sensor.mailbox_hatch
        state: 'open'
    action:
      - service: notify.Mailgun_Notifier
        data:
          title: 'Mailbox Hatch has been opened'
          message: 'Mailbox Hatch has been opened'

  - alias: Repeat Mailbox statuses every hour
    trigger:
      - platform: time
        # Matches every hour at 27 minutes past whole
        minutes: 27
        seconds: 00
    action:
      - service: mqtt.publish
        data:
         topic: "/outside/mailbox/deposits/"
         payload_template:  "{{ states('sensor.mailbox_deposits') }}"
      - service: mqtt.publish
        data:
         topic: "/outside/mailbox/hatch/"
         payload_template:  "{{ states('sensor.mailbox_hatch') }}"
      - service: mqtt.publish
        data:
         topic: "/outside/mailbox/door/"
         payload_template:  "{{ states('sensor.mailbox_door') }}"




  #### Renew SSL Cert ####
  - alias: 'Auto Renew SSL Cert'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl
  - alias: 'SSL expiry notification'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
    action:
      service: notify.Mailgun_Notifier
      data:
        title: 'SSL Cert warning'
        message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'
