####### AUTOMATION #######
# Verisure automation

  - alias: Alarm status changed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_1
    action:
      - service: notify.notify
        data_template:
          message: >
            Alarm changed from {{ trigger.from_state.state }}
            to {{ trigger.to_state.state }}
            by {{ trigger.to_state.attributes.changed_by }}
  
  ####### FRONT DOOR ######
  - alias: Turn on front door light at sunset
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunset
    # Optional time offset. This example is 45 minutes.
        offset: '-00:20:00'
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_front_door

  - alias: Turn off front door light at 23:00
    trigger:
      - platform: time
        after: '23:00:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_front_door

  - alias: Turn on front door light at 06:30
    trigger:
      - platform: time
        after: '06:30:00'
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_front_door

  - alias: Turn off front door light at sunrise
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunrise
    # Optional time offset. This example is 45 minutes.
        offset: '+00:20:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_front_door


  ####### AQUARIUM ######
  - alias: Turn on aquarium at 07:00
    trigger:
      - platform: time
        after: '07:00:00'
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.dining_room_aquarium

  - alias: Turn off aquarium at 21:30
    trigger:
      - platform: time
        after: '21:30:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.dining_room_aquarium

  ####### DRIVEWAY ######
  - alias: Turn on DRIVEWAY light at sunset
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunset
    # Optional time offset. This example is 45 minutes.
        offset: '+00:40:00'
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_driveway

  - alias: Turn off DRIVEWAY light at 22:00
    trigger:
      - platform: time
        after: '22:00:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_driveway

  - alias: Turn on DRIVEWAY light at 07:00
    trigger:
      - platform: time
        after: '07:00:00'
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.garden_driveway

  - alias: Turn off DRIVEWAY light at sunrise
    trigger:
      - platform: sun
    # Possible values: sunset, sunrise
        event: sunrise
    # Optional time offset. This example is 45 minutes.
        offset: '+00:00:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.garden_driveway

  ####### STAIRS ######
  - alias: Turn on Stairs light at sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:10:00'
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_stairs

  - alias: Turn off Stairs light at 23:00
    trigger:
      - platform: time
        after: '23:00:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.hallway_stairs

  - alias: Turn on Stairs light at 06:30
    trigger:
      - platform: time
        after: '06:30:00'
    condition:
      - condition: template
        value_template: '{{ states.sun.sun.attributes.elevation < 0 }}' #only if sun is down
    action: 
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_stairs

  - alias: Turn off Stairs light at sunrise
    trigger:
      - platform: sun
        event: sunrise
        offset: '00:01:00'
    action: 
      - service: homeassistant.turn_off
        entity_id:
          - switch.hallway_stairs 