  # livingroom_switch_left_status:
  #   name: Living room switch left status
  #   initial: 'off'
  #   options:
  #     - 'off'
  #     - 'single'
  #     - 'double'
  #     - 'long'

  ## These automations are used to set the status of an aqara button to either off, single, double or long. 
  ## The Aqara buttons does not support this out of the box, so this is a way to emulate it with automations and input selects.
  ## A bit of a hack, but should work. Have to be repeated for left button, right button and both buttons in order to get it all to work.
  ## Then the input select can be used for automations rather than using the on/off directly. Since the Aqara buttons only show up
  ## as a binary sensor, it can only have two values, on or off.
  - alias: Livingroom switch left button single click
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d000171d630
          click_type: single
    condition:
      - condition: state
        entity_id: input_select.livingroom_switch_left_status
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.livingroom_switch_left_status
          option: 'single'


  - alias: Livingroom switch left button double click ceiling is on
    trigger:
      #- platform: event
      #  event_type: click
      #  event_data:
      #    entity_id: binary_sensor.wall_switch_left_158d000171d630
      #    click_type: single
      - platform: state
        entity_id: input_select.livingroom_switch_left_status
        to: 'double'
    condition:
      - condition: state
        entity_id: light.living_room_roof_1
        state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - group.livingroom_ceiling

  - alias: Livingroom switch left button double click ceiling is off
    trigger:
      #- platform: event
      #  event_type: click
      #  event_data:
      #    entity_id: binary_sensor.wall_switch_left_158d000171d630
      #    click_type: single
      - platform: state
        entity_id: input_select.livingroom_switch_left_status
        to: 'double'
    condition:
      - condition: state
        entity_id: light.living_room_roof_1
        state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: 
          - group.livingroom_ceiling

  - alias: Livingroom switch left button single press increase number
    trigger:
      - platform: state
        entity_id: input_select.livingroom_switch_left_status
        to: 'single'
        for:
          seconds: 2
    action:
      - service: input_number.set_value
        data_template: 
          entity_id: input_number.livingroom_switch_left_number
          value: '{{ states.input_number.livingroom_switch_left_number.state | int + 17 }}'
      - service: input_select.select_option
        data:
          entity_id: input_select.livingroom_switch_left_status
          option: 'off'
      

  - alias: Set livingroom switch state to 5 if over 100
    trigger:
      - platform: state
        entity_id: input_number.livingroom_switch_left_number
    condition:
      - condition: template
        value_template: '{{ input_number.livingroom_switch_left_number.state > 100 }}'
    action:
      - service: input_number.set_value
        data_template: 
          entity_id: input_number.livingroom_switch_left_number
          value: '5'


  - alias: Livingroom switch left button set to off
    trigger:
      - platform: state
        entity_id: input_select.livingroom_switch_left_status
        to: 'single'
        for:
          seconds: 3
      - platform: state
        entity_id: input_select.livingroom_switch_left_status
        to: 'double'
        for:
          seconds: 3
      - platform: state
        entity_id: input_select.livingroom_switch_left_status
        to: 'long'
        for:
          seconds: 3
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.livingroom_switch_left_status
          option: 'off'

  #- alias: Livingroom switch left button long click
  #  trigger:
  #    - platform: event
  #      event_type: click
  #      event_data:
  #        entity_id: binary_sensor.wall_switch_left_158d000171d630
  #        click_type: single
  #      for: 
  #        seconds: 1
  #  action:
  #    - service: input_select.select_option
  #      data:
  #        entity_id: input_select.livingroom_switch_left_status
  #        option: 'long'

  - alias: Livingroom switch left button double click
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.wall_switch_left_158d000171d630
          click_type: single
    condition: 
      - condition: state
        entity_id: input_select.livingroom_switch_left_status
        state: 'single'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.livingroom_switch_left_status
          option: 'double'

